import { useEffect, useState } from "react";
import api from "../services/api";
import { canUseDeviceNotifications, disableDeviceNotifications, enableDeviceNotifications } from "../utils/deviceNotifications";

const bell = "\u{1F514}";

export default function NotificationBell({ mobile = false }) {
  const [items, setItems] = useState([]);
  const [unreadCount, setUnreadCount] = useState(0);
  const [open, setOpen] = useState(false);
  const [busy, setBusy] = useState(false);
  const [message, setMessage] = useState("");
  const [deviceEnabled, setDeviceEnabled] = useState(() => typeof Notification !== "undefined" && Notification.permission === "granted");
  const load = async () => { try { const response = await api.get("/api/notifications", { params: { limit: 20 } }); setItems(response.data?.data || []); setUnreadCount(Number(response.data?.meta?.unread_count || 0)); } catch { /* A temporary error must not interrupt the portal. */ } };
  useEffect(() => { load(); const timer = window.setInterval(load, 60000); return () => window.clearInterval(timer); }, []);
  const markRead = async (ids, all = false) => { try { await api.post("/api/notifications/read", all ? { all: true } : { ids }); setItems((current) => current.map((item) => all || ids.includes(item.id) ? { ...item, read_at: item.read_at || new Date().toISOString() } : item)); setUnreadCount((current) => all ? 0 : Math.max(0, current - ids.length)); } catch { setMessage("We could not update the notification yet."); } };
  const openItem = async (item) => { if (!item.read_at) await markRead([item.id]); if (item.url) window.location.assign(item.url); };
  const toggleDeviceAlerts = async () => { setBusy(true); setMessage(""); try { if (deviceEnabled) { await disableDeviceNotifications(); setDeviceEnabled(false); setMessage("Device notifications turned off."); } else { await enableDeviceNotifications(); setDeviceEnabled(true); setMessage("Device notifications turned on."); } } catch (error) { setMessage(error.response?.data?.message || error.message || "Could not update device notifications."); } finally { setBusy(false); } };
  return <div style={{ position: "fixed", top: mobile ? 64 : 16, right: mobile ? 64 : 18, zIndex: 42 }}><button type="button" onClick={() => setOpen((current) => !current)} aria-label="Open notifications" style={{ position: "relative", width: 42, height: 42, borderRadius: 12, border: "1px solid #cbd5e1", background: "#fff", color: "#0f172a", fontSize: 20, cursor: "pointer", boxShadow: "0 7px 18px rgba(15,23,42,.16)" }}>{bell}{unreadCount > 0 ? <span style={{ position: "absolute", top: -6, right: -6, minWidth: 19, height: 19, padding: "0 4px", borderRadius: 999, background: "#b91c1c", color: "#fff", fontSize: 11, lineHeight: "19px", fontWeight: 800 }}>{unreadCount > 99 ? "99+" : unreadCount}</span> : null}</button>{open ? <section aria-label="Notifications" style={{ position: "absolute", top: 50, right: 0, width: "min(360px, calc(100vw - 28px))", maxHeight: "min(560px, calc(100vh - 86px))", overflowY: "auto", background: "#fff", border: "1px solid #dbe3ef", borderRadius: 14, boxShadow: "0 18px 44px rgba(15,23,42,.22)", padding: 12 }}><div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 10 }}><strong style={{ color: "#0f172a" }}>Notifications</strong>{unreadCount > 0 ? <button type="button" onClick={() => markRead([], true)} style={{ border: 0, background: "transparent", color: "#1d4ed8", cursor: "pointer", fontWeight: 700, fontSize: 12 }}>Mark all read</button> : null}</div>{canUseDeviceNotifications() ? <button type="button" disabled={busy} onClick={toggleDeviceAlerts} style={{ width: "100%", marginTop: 10, padding: "8px 10px", borderRadius: 8, border: "1px solid #bfdbfe", background: "#eff6ff", color: "#1d4ed8", fontWeight: 700, cursor: busy ? "wait" : "pointer" }}>{busy ? "Updating..." : deviceEnabled ? "Turn off device alerts" : "Turn on device alerts"}</button> : null}{message ? <p style={{ margin: "8px 0 0", color: "#334155", fontSize: 12 }}>{message}</p> : null}<div style={{ marginTop: 10 }}>{items.length === 0 ? <p style={{ margin: "12px 0", color: "#64748b", fontSize: 13 }}>No notifications yet.</p> : items.map((item) => <button type="button" key={item.id} onClick={() => openItem(item)} style={{ width: "100%", display: "block", textAlign: "left", padding: "10px 8px", border: 0, borderTop: "1px solid #eef2f7", background: item.read_at ? "#fff" : "#eff6ff", color: "#0f172a", cursor: "pointer" }}><strong style={{ display: "block", fontSize: 13 }}>{item.title}</strong><span style={{ display: "block", marginTop: 3, fontSize: 12, color: "#475569", lineHeight: 1.35 }}>{item.message}</span><span style={{ display: "block", marginTop: 5, fontSize: 11, color: "#64748b" }}>{item.created_at ? new Date(item.created_at).toLocaleString() : ""}</span></button>)}</div></section> : null}</div>;
}